drop function if exists public.publish_marketplace_preset(text, text, text, text, text[], text, text, text);
drop function if exists public.publish_marketplace_preset(text, text, text, text, text[], text, text, text, boolean);
drop function if exists public.publish_marketplace_preset(text, text, text, text, text[], text, text, text, text, boolean);
drop function if exists public.update_marketplace_preset_metadata(uuid, text, text, text[], text, text);
drop function if exists public.update_marketplace_preset_metadata(uuid, text, text, text[], text, text, boolean);
drop function if exists public.update_marketplace_preset_metadata(uuid, text, text, text[], text, text, boolean, text, text);
drop function if exists public.is_marketplace_moderator(uuid);
drop function if exists public.list_manageable_marketplace_presets();

create table if not exists public.marketplace_publish_events (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users (id) on delete cascade,
    created_at timestamptz not null default now()
);

create index if not exists marketplace_publish_events_user_created_idx
    on public.marketplace_publish_events (user_id, created_at desc);

create table if not exists public.marketplace_like_events (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users (id) on delete cascade,
    preset_id uuid not null references public.marketplace_presets (id) on delete cascade,
    created_at timestamptz not null default now()
);

create index if not exists marketplace_like_events_user_preset_created_idx
    on public.marketplace_like_events (user_id, preset_id, created_at desc);

create table if not exists public.marketplace_download_events (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users (id) on delete cascade,
    preset_id uuid not null references public.marketplace_presets (id) on delete cascade,
    created_at timestamptz not null default now()
);

create index if not exists marketplace_download_events_user_preset_created_idx
    on public.marketplace_download_events (user_id, preset_id, created_at desc);

create or replace function public.is_marketplace_moderator(target_user_id uuid default auth.uid())
returns boolean
language sql
security definer
set search_path = public, pg_temp
as $$
    select exists (
        select 1
        from public.marketplace_roles
        where user_id = coalesce(target_user_id, auth.uid())
          and role in ('moderator', 'admin')
    );
$$;

create or replace function public.publish_marketplace_preset(
    preset_slug text,
    preset_name text,
    preset_author_name text,
    preset_description text,
    preset_tags text[],
    preset_game_version text,
    preset_pathmind_version text,
    preset_storage_bucket text,
    preset_file_path text,
    preset_published boolean default true
)
returns public.marketplace_presets
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    user_preset_count integer;
    last_publish_at timestamptz;
    publishes_last_minute integer;
    inserted_row public.marketplace_presets;
    normalized_tags text[];
begin
    if auth.uid() is null then
        raise exception 'Authentication required.'
            using errcode = '42501';
    end if;

    if coalesce(trim(preset_slug), '') = '' then
        raise exception 'Preset slug is required.'
            using errcode = 'P0001';
    end if;

    if coalesce(trim(preset_name), '') = '' then
        raise exception 'Preset name is required.'
            using errcode = 'P0001';
    end if;

    if coalesce(trim(preset_file_path), '') = '' then
        raise exception 'Preset file path is required.'
            using errcode = 'P0001';
    end if;

    select count(*)
    into user_preset_count
    from public.marketplace_presets
    where author_user_id = auth.uid();

    if user_preset_count >= 32 then
        raise exception 'You have reached the maximum of 32 presets. Delete one to publish another.'
            using errcode = 'P0001';
    end if;

    -- At least 10s since last publish (max(created_at) avoids edge cases with count-based windows).
    select max(created_at)
    into last_publish_at
    from public.marketplace_publish_events
    where user_id = auth.uid();

    if last_publish_at is not null and last_publish_at > now() - interval '10 seconds' then
        raise exception 'Publish rate limit exceeded. Wait at least 10 seconds between publishes.'
            using errcode = 'P0001';
    end if;

    select count(*)
    into publishes_last_minute
    from public.marketplace_publish_events
    where user_id = auth.uid()
      and created_at >= now() - interval '1 minute';

    if publishes_last_minute >= 6 then
        raise exception 'Publish rate limit exceeded. You can publish at most 6 times per minute.'
            using errcode = 'P0001';
    end if;

    insert into public.marketplace_publish_events (user_id)
    values (auth.uid());

    select coalesce(array_agg(tag), array[]::text[])
    into normalized_tags
    from (
        select distinct left(trim(tag), 32) as tag
        from unnest(coalesce(preset_tags, array[]::text[])) as tag
        where coalesce(trim(tag), '') <> ''
        limit 12
    ) normalized;

    insert into public.marketplace_presets (
        slug,
        name,
        author_name,
        description,
        tags,
        game_version,
        pathmind_version,
        storage_bucket,
        file_path,
        published,
        author_user_id
    )
    values (
        trim(preset_slug),
        left(trim(preset_name), 64),
        coalesce(nullif(trim(preset_author_name), ''), 'Discord user'),
        left(coalesce(trim(preset_description), ''), 180),
        normalized_tags,
        nullif(trim(preset_game_version), ''),
        nullif(trim(preset_pathmind_version), ''),
        coalesce(nullif(trim(preset_storage_bucket), ''), 'graphs'),
        trim(preset_file_path),
        coalesce(preset_published, true),
        auth.uid()
    )
    returning *
    into inserted_row;

    return inserted_row;
end;
$$;

create or replace function public.delete_marketplace_preset(target_preset_id uuid)
returns public.marketplace_presets
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    deleted_row public.marketplace_presets;
begin
    if auth.uid() is null then
        raise exception 'Authentication required.'
            using errcode = '42501';
    end if;

    select *
    into deleted_row
    from public.marketplace_presets
    where id = target_preset_id
      and (
          author_user_id = auth.uid()
          or public.is_marketplace_moderator(auth.uid())
      );

    if deleted_row.id is null then
        raise exception 'Preset not found or not owned by current user.'
            using errcode = '42501';
    end if;

    delete from public.preset_likes
    where preset_id = target_preset_id;

    delete from public.marketplace_presets
    where id = target_preset_id
      and (
          author_user_id = auth.uid()
          or public.is_marketplace_moderator(auth.uid())
      )
    returning *
    into deleted_row;

    if deleted_row.id is null then
        raise exception 'Preset delete failed.'
            using errcode = 'P0001';
    end if;

    return deleted_row;
end;
$$;

create or replace function public.update_marketplace_preset_metadata(
    target_preset_id uuid,
    preset_name text,
    preset_description text,
    preset_tags text[],
    preset_game_version text,
    preset_pathmind_version text,
    preset_published boolean default null,
    preset_storage_bucket text default null,
    preset_file_path text default null
)
returns public.marketplace_presets
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    updated_row public.marketplace_presets;
    normalized_tags text[];
begin
    if auth.uid() is null then
        raise exception 'Authentication required.'
            using errcode = '42501';
    end if;

    if coalesce(trim(preset_name), '') = '' then
        raise exception 'Preset name is required.'
            using errcode = 'P0001';
    end if;

    select coalesce(array_agg(tag), array[]::text[])
    into normalized_tags
    from (
        select distinct left(trim(tag), 32) as tag
        from unnest(coalesce(preset_tags, array[]::text[])) as tag
        where coalesce(trim(tag), '') <> ''
        limit 12
    ) normalized;

    update public.marketplace_presets
    set name = left(trim(preset_name), 64),
        description = left(coalesce(trim(preset_description), ''), 180),
        tags = normalized_tags,
        game_version = nullif(trim(preset_game_version), ''),
        pathmind_version = nullif(trim(preset_pathmind_version), ''),
        published = coalesce(preset_published, published),
        storage_bucket = coalesce(nullif(trim(preset_storage_bucket), ''), storage_bucket),
        file_path = coalesce(nullif(trim(preset_file_path), ''), file_path),
        updated_at = now()
    where id = target_preset_id
      and (
          author_user_id = auth.uid()
          or public.is_marketplace_moderator(auth.uid())
      )
    returning *
    into updated_row;

    if updated_row.id is null then
        raise exception 'Preset not found or not owned by current user.'
            using errcode = '42501';
    end if;

    return updated_row;
end;
$$;

create or replace function public.list_manageable_marketplace_presets()
returns setof public.marketplace_presets
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    if auth.uid() is null then
        raise exception 'Authentication required.'
            using errcode = '42501';
    end if;

    if public.is_marketplace_moderator(auth.uid()) then
        return query
        select *
        from public.marketplace_presets
        order by updated_at desc;
    end if;

    return query
    select *
    from public.marketplace_presets
    where author_user_id = auth.uid()
    order by updated_at desc;
end;
$$;

create or replace function public.toggle_marketplace_preset_like(target_preset_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    recent_like_count integer;
    liked_now boolean;
    updated_likes_count integer;
begin
    if auth.uid() is null then
        raise exception 'Authentication required.'
            using errcode = '42501';
    end if;

    if not exists (
        select 1
        from public.marketplace_presets
        where id = target_preset_id
          and published = true
    ) then
        raise exception 'Preset not found.'
            using errcode = 'P0001';
    end if;

    select count(*)
    into recent_like_count
    from public.marketplace_like_events
    where user_id = auth.uid()
      and preset_id = target_preset_id
      and created_at >= now() - interval '2500 milliseconds';

    if recent_like_count > 0 then
        raise exception 'Like rate limit exceeded. Try again in a moment.'
            using errcode = 'P0001';
    end if;

    insert into public.marketplace_like_events (user_id, preset_id)
    values (auth.uid(), target_preset_id);

    if exists (
        select 1
        from public.preset_likes
        where preset_id = target_preset_id
          and user_id = auth.uid()
    ) then
        delete from public.preset_likes
        where preset_id = target_preset_id
          and user_id = auth.uid();
        liked_now := false;
    else
        insert into public.preset_likes (preset_id, user_id)
        values (target_preset_id, auth.uid());
        liked_now := true;
    end if;

    select count(*)
    into updated_likes_count
    from public.preset_likes
    where preset_id = target_preset_id;

    update public.marketplace_presets
    set likes_count = updated_likes_count,
        updated_at = now()
    where id = target_preset_id;

    return jsonb_build_object(
        'liked', liked_now,
        'likes_count', updated_likes_count
    );
end;
$$;

create or replace function public.increment_preset_downloads(target_preset_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    recent_download_count integer;
    updated_downloads_count integer;
begin
    if auth.uid() is null then
        raise exception 'Authentication required.'
            using errcode = '42501';
    end if;

    if not exists (
        select 1
        from public.marketplace_presets
        where id = target_preset_id
          and published = true
    ) then
        raise exception 'Preset not found.'
            using errcode = 'P0001';
    end if;

    select count(*)
    into recent_download_count
    from public.marketplace_download_events
    where user_id = auth.uid()
      and preset_id = target_preset_id
      and created_at >= now() - interval '2500 milliseconds';

    if recent_download_count = 0 then
        insert into public.marketplace_download_events (user_id, preset_id)
        values (auth.uid(), target_preset_id);

        update public.marketplace_presets
        set downloads_count = coalesce(downloads_count, 0) + 1,
            updated_at = now()
        where id = target_preset_id
        returning downloads_count
        into updated_downloads_count;
    else
        select downloads_count
        into updated_downloads_count
        from public.marketplace_presets
        where id = target_preset_id;
    end if;

    return jsonb_build_object(
        'downloaded', true,
        'downloads_count', coalesce(updated_downloads_count, 0)
    );
end;
$$;

revoke all on function public.is_marketplace_moderator(uuid) from public;
revoke all on function public.publish_marketplace_preset(text, text, text, text, text[], text, text, text, text, boolean) from public;
revoke all on function public.delete_marketplace_preset(uuid) from public;
revoke all on function public.update_marketplace_preset_metadata(uuid, text, text, text[], text, text, boolean, text, text) from public;
revoke all on function public.list_manageable_marketplace_presets() from public;
revoke all on function public.toggle_marketplace_preset_like(uuid) from public;
revoke all on function public.increment_preset_downloads(uuid) from public;

grant execute on function public.is_marketplace_moderator(uuid) to authenticated;
grant execute on function public.publish_marketplace_preset(text, text, text, text, text[], text, text, text, text, boolean) to authenticated;
grant execute on function public.delete_marketplace_preset(uuid) to authenticated;
grant execute on function public.update_marketplace_preset_metadata(uuid, text, text, text[], text, text, boolean, text, text) to authenticated;
grant execute on function public.list_manageable_marketplace_presets() to authenticated;
grant execute on function public.toggle_marketplace_preset_like(uuid) to authenticated;
grant execute on function public.increment_preset_downloads(uuid) to authenticated;
