version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directories:
      - "/"
      - "/common"
      - "/mc26/fabric"
      - "/mc26/neoforge"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build"
    groups:
      gradle-minor-and-patch:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "net.darkhax.curseforgegradle*"
        versions: [">=1.2.30"]
