drop extension if exists "pg_net";


  create table "public"."marketplace_author_profiles" (
    "user_id" uuid not null,
    "display_name" text not null default 'Discord user'::text,
    "avatar_url" text,
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."marketplace_author_profiles" enable row level security;


  create table "public"."marketplace_download_events" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "preset_id" uuid not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."marketplace_download_events" enable row level security;


  create table "public"."marketplace_like_events" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "preset_id" uuid not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."marketplace_like_events" enable row level security;


  create table "public"."marketplace_presets" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "slug" text not null,
    "name" text not null,
    "author_name" text not null,
    "description" text not null default ''::text,
    "tags" text[] not null default '{}'::text[],
    "game_version" text,
    "pathmind_version" text,
    "likes_count" integer not null default 0,
    "downloads_count" integer not null default 0,
    "file_path" text not null,
    "published" boolean not null default true,
    "updated_at" timestamp with time zone not null default now(),
    "author_user_id" uuid,
    "storage_bucket" text not null default 'graphs'::text,
    "author_avatar_url" text
      );


alter table "public"."marketplace_presets" enable row level security;


  create table "public"."marketplace_publish_events" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."marketplace_publish_events" enable row level security;


  create table "public"."marketplace_roles" (
    "user_id" uuid not null,
    "role" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."marketplace_roles" enable row level security;


  create table "public"."preset_likes" (
    "preset_id" uuid not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."preset_likes" enable row level security;

CREATE UNIQUE INDEX marketplace_author_profiles_pkey ON public.marketplace_author_profiles USING btree (user_id);

CREATE UNIQUE INDEX marketplace_download_events_pkey ON public.marketplace_download_events USING btree (id);

CREATE INDEX marketplace_download_events_user_preset_created_idx ON public.marketplace_download_events USING btree (user_id, preset_id, created_at DESC);

CREATE UNIQUE INDEX marketplace_like_events_pkey ON public.marketplace_like_events USING btree (id);

CREATE INDEX marketplace_like_events_user_preset_created_idx ON public.marketplace_like_events USING btree (user_id, preset_id, created_at DESC);

CREATE UNIQUE INDEX marketplace_presets_pkey ON public.marketplace_presets USING btree (id);

CREATE UNIQUE INDEX marketplace_presets_slug_key ON public.marketplace_presets USING btree (slug);

CREATE UNIQUE INDEX marketplace_publish_events_pkey ON public.marketplace_publish_events USING btree (id);

CREATE INDEX marketplace_publish_events_user_created_idx ON public.marketplace_publish_events USING btree (user_id, created_at DESC);

CREATE UNIQUE INDEX marketplace_roles_pkey ON public.marketplace_roles USING btree (user_id);

CREATE UNIQUE INDEX preset_likes_pkey ON public.preset_likes USING btree (preset_id, user_id);

alter table "public"."marketplace_author_profiles" add constraint "marketplace_author_profiles_pkey" PRIMARY KEY using index "marketplace_author_profiles_pkey";

alter table "public"."marketplace_download_events" add constraint "marketplace_download_events_pkey" PRIMARY KEY using index "marketplace_download_events_pkey";

alter table "public"."marketplace_like_events" add constraint "marketplace_like_events_pkey" PRIMARY KEY using index "marketplace_like_events_pkey";

alter table "public"."marketplace_presets" add constraint "marketplace_presets_pkey" PRIMARY KEY using index "marketplace_presets_pkey";

alter table "public"."marketplace_publish_events" add constraint "marketplace_publish_events_pkey" PRIMARY KEY using index "marketplace_publish_events_pkey";

alter table "public"."marketplace_roles" add constraint "marketplace_roles_pkey" PRIMARY KEY using index "marketplace_roles_pkey";

alter table "public"."preset_likes" add constraint "preset_likes_pkey" PRIMARY KEY using index "preset_likes_pkey";

alter table "public"."marketplace_author_profiles" add constraint "marketplace_author_profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."marketplace_author_profiles" validate constraint "marketplace_author_profiles_user_id_fkey";

alter table "public"."marketplace_download_events" add constraint "marketplace_download_events_preset_id_fkey" FOREIGN KEY (preset_id) REFERENCES public.marketplace_presets(id) ON DELETE CASCADE not valid;

alter table "public"."marketplace_download_events" validate constraint "marketplace_download_events_preset_id_fkey";

alter table "public"."marketplace_download_events" add constraint "marketplace_download_events_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."marketplace_download_events" validate constraint "marketplace_download_events_user_id_fkey";

alter table "public"."marketplace_like_events" add constraint "marketplace_like_events_preset_id_fkey" FOREIGN KEY (preset_id) REFERENCES public.marketplace_presets(id) ON DELETE CASCADE not valid;

alter table "public"."marketplace_like_events" validate constraint "marketplace_like_events_preset_id_fkey";

alter table "public"."marketplace_like_events" add constraint "marketplace_like_events_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."marketplace_like_events" validate constraint "marketplace_like_events_user_id_fkey";

alter table "public"."marketplace_presets" add constraint "marketplace_presets_author_user_id_fkey" FOREIGN KEY (author_user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."marketplace_presets" validate constraint "marketplace_presets_author_user_id_fkey";

alter table "public"."marketplace_presets" add constraint "marketplace_presets_description_len" CHECK ((length(description) <= 180)) not valid;

alter table "public"."marketplace_presets" validate constraint "marketplace_presets_description_len";

alter table "public"."marketplace_presets" add constraint "marketplace_presets_name_len" CHECK ((length(name) <= 64)) not valid;

alter table "public"."marketplace_presets" validate constraint "marketplace_presets_name_len";

alter table "public"."marketplace_presets" add constraint "marketplace_presets_name_not_blank" CHECK ((length(TRIM(BOTH FROM name)) > 0)) not valid;

alter table "public"."marketplace_presets" validate constraint "marketplace_presets_name_not_blank";

alter table "public"."marketplace_presets" add constraint "marketplace_presets_slug_key" UNIQUE using index "marketplace_presets_slug_key";

alter table "public"."marketplace_publish_events" add constraint "marketplace_publish_events_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."marketplace_publish_events" validate constraint "marketplace_publish_events_user_id_fkey";

alter table "public"."marketplace_roles" add constraint "marketplace_roles_role_check" CHECK ((role = ANY (ARRAY['moderator'::text, 'admin'::text]))) not valid;

alter table "public"."marketplace_roles" validate constraint "marketplace_roles_role_check";

alter table "public"."marketplace_roles" add constraint "marketplace_roles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."marketplace_roles" validate constraint "marketplace_roles_user_id_fkey";

alter table "public"."preset_likes" add constraint "preset_likes_preset_id_fkey" FOREIGN KEY (preset_id) REFERENCES public.marketplace_presets(id) ON DELETE CASCADE not valid;

alter table "public"."preset_likes" validate constraint "preset_likes_preset_id_fkey";

alter table "public"."preset_likes" add constraint "preset_likes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."preset_likes" validate constraint "preset_likes_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.delete_marketplace_preset(target_preset_id uuid)
 RETURNS public.marketplace_presets
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
    deleted_row public.marketplace_presets;
begin
    if auth.uid() is null then
        raise exception 'Authentication required.'
            using errcode = '42501';
    end if;

    select *
    into deleted_row
    from public.marketplace_presets
    where id = target_preset_id
      and (
          author_user_id = auth.uid()
          or public.is_marketplace_moderator(auth.uid())
      );

    if deleted_row.id is null then
        raise exception 'Preset not found or not owned by current user.'
            using errcode = '42501';
    end if;

    delete from public.preset_likes
    where preset_id = target_preset_id;

    delete from public.marketplace_presets
    where id = target_preset_id
      and (
          author_user_id = auth.uid()
          or public.is_marketplace_moderator(auth.uid())
      )
    returning *
    into deleted_row;

    if deleted_row.id is null then
        raise exception 'Preset delete failed.'
            using errcode = 'P0001';
    end if;

    return deleted_row;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_preset_downloads(target_preset_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
    recent_download_count integer;
    updated_downloads_count integer;
begin
    if auth.uid() is null then
        raise exception 'Authentication required.'
            using errcode = '42501';
    end if;

    if not exists (
        select 1
        from public.marketplace_presets
        where id = target_preset_id
          and published = true
    ) then
        raise exception 'Preset not found.'
            using errcode = 'P0001';
    end if;

    select count(*)
    into recent_download_count
    from public.marketplace_download_events
    where user_id = auth.uid()
      and preset_id = target_preset_id
      and created_at >= now() - interval '2500 milliseconds';

    if recent_download_count = 0 then
        insert into public.marketplace_download_events (user_id, preset_id)
        values (auth.uid(), target_preset_id);

        update public.marketplace_presets
        set downloads_count = coalesce(downloads_count, 0) + 1,
            updated_at = now()
        where id = target_preset_id
        returning downloads_count
        into updated_downloads_count;
    else
        select downloads_count
        into updated_downloads_count
        from public.marketplace_presets
        where id = target_preset_id;
    end if;

    return jsonb_build_object(
        'downloaded', true,
        'downloads_count', coalesce(updated_downloads_count, 0)
    );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.is_marketplace_moderator(target_user_id uuid DEFAULT auth.uid())
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
    select exists (
        select 1
        from public.marketplace_roles
        where user_id = coalesce(target_user_id, auth.uid())
          and role in ('moderator', 'admin')
    );
$function$
;

CREATE OR REPLACE FUNCTION public.list_manageable_marketplace_presets()
 RETURNS SETOF public.marketplace_presets
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
begin
    if auth.uid() is null then
        raise exception 'Authentication required.'
            using errcode = '42501';
    end if;

    if public.is_marketplace_moderator(auth.uid()) then
        return query
        select *
        from public.marketplace_presets
        order by updated_at desc nulls last, created_at desc nulls last;
    end if;

    return query
    select *
    from public.marketplace_presets
    where author_user_id = auth.uid()
    order by updated_at desc nulls last, created_at desc nulls last;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.publish_marketplace_preset(preset_slug text, preset_name text, preset_author_name text, preset_description text, preset_tags text[], preset_game_version text, preset_pathmind_version text, preset_file_path text, preset_published boolean DEFAULT true)
 RETURNS public.marketplace_presets
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
    user_preset_count integer;
    last_publish_at timestamptz;
    publishes_last_minute integer;
    inserted_row public.marketplace_presets;
    normalized_tags text[];
begin
    if auth.uid() is null then
        raise exception 'Authentication required.'
            using errcode = '42501';
    end if;

    if coalesce(trim(preset_slug), '') = '' then
        raise exception 'Preset slug is required.'
            using errcode = 'P0001';
    end if;

    if coalesce(trim(preset_name), '') = '' then
        raise exception 'Preset name is required.'
            using errcode = 'P0001';
    end if;

    if coalesce(trim(preset_file_path), '') = '' then
        raise exception 'Preset file path is required.'
            using errcode = 'P0001';
    end if;

    select count(*)
    into user_preset_count
    from public.marketplace_presets
    where author_user_id = auth.uid();

    if user_preset_count >= 32 then
        raise exception 'You have reached the maximum of 32 presets. Delete one to publish another.'
            using errcode = 'P0001';
    end if;

    select max(created_at)
    into last_publish_at
    from public.marketplace_publish_events
    where user_id = auth.uid();

    if last_publish_at is not null and last_publish_at > now() - interval '10 seconds' then
        raise exception 'Publish rate limit exceeded. Wait at least 10 seconds between publishes.'
            using errcode = 'P0001';
    end if;

    select count(*)
    into publishes_last_minute
    from public.marketplace_publish_events
    where user_id = auth.uid()
      and created_at >= now() - interval '1 minute';

    if publishes_last_minute >= 6 then
        raise exception 'Publish rate limit exceeded. You can publish at most 6 times per minute.'
            using errcode = 'P0001';
    end if;

    insert into public.marketplace_publish_events (user_id)
    values (auth.uid());

    select coalesce(array_agg(tag), array[]::text[])
    into normalized_tags
    from (
        select distinct left(trim(tag), 32) as tag
        from unnest(coalesce(preset_tags, array[]::text[])) as tag
        where coalesce(trim(tag), '') <> ''
        limit 12
    ) normalized;

    insert into public.marketplace_presets (
        slug,
        name,
        author_name,
        description,
        tags,
        game_version,
        pathmind_version,
        file_path,
        published,
        author_user_id
    )
    values (
        trim(preset_slug),
        left(trim(preset_name), 64),
        coalesce(nullif(trim(preset_author_name), ''), 'Discord user'),
        left(coalesce(trim(preset_description), ''), 180),
        normalized_tags,
        nullif(trim(preset_game_version), ''),
        nullif(trim(preset_pathmind_version), ''),
        trim(preset_file_path),
        coalesce(preset_published, true),
        auth.uid()
    )
    returning *
    into inserted_row;

    return inserted_row;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.publish_marketplace_preset(preset_slug text, preset_name text, preset_author_name text, preset_description text, preset_tags text[], preset_game_version text, preset_pathmind_version text, preset_storage_bucket text, preset_file_path text, preset_published boolean DEFAULT true)
 RETURNS public.marketplace_presets
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
    recent_publish_count integer;
    inserted_row public.marketplace_presets;
    normalized_tags text[];
begin
    if auth.uid() is null then
        raise exception 'Authentication required.'
            using errcode = '42501';
    end if;

    if coalesce(trim(preset_slug), '') = '' then
        raise exception 'Preset slug is required.'
            using errcode = 'P0001';
    end if;

    if coalesce(trim(preset_name), '') = '' then
        raise exception 'Preset name is required.'
            using errcode = 'P0001';
    end if;

    if coalesce(trim(preset_file_path), '') = '' then
        raise exception 'Preset file path is required.'
            using errcode = 'P0001';
    end if;

    if coalesce(trim(preset_storage_bucket), '') = '' then
        raise exception 'Preset storage bucket is required.'
            using errcode = 'P0001';
    end if;

    select count(*)
    into recent_publish_count
    from public.marketplace_publish_events
    where user_id = auth.uid()
      and created_at >= now() - interval '10 minutes';

    if recent_publish_count >= 5 then
        raise exception 'Publish rate limit exceeded. Try again in a few minutes.'
            using errcode = 'P0001';
    end if;

    insert into public.marketplace_publish_events (user_id)
    values (auth.uid());

    select coalesce(array_agg(tag), array[]::text[])
    into normalized_tags
    from (
        select distinct left(trim(tag), 32) as tag
        from unnest(coalesce(preset_tags, array[]::text[])) as tag
        where coalesce(trim(tag), '') <> ''
        limit 12
    ) normalized;

    insert into public.marketplace_presets (
        slug,
        name,
        author_name,
        description,
        tags,
        game_version,
        pathmind_version,
        storage_bucket,
        file_path,
        published,
        author_user_id
    )
    values (
        trim(preset_slug),
        left(trim(preset_name), 64),
        coalesce(nullif(trim(preset_author_name), ''), 'Discord user'),
        left(coalesce(trim(preset_description), ''), 180),
        normalized_tags,
        nullif(trim(preset_game_version), ''),
        nullif(trim(preset_pathmind_version), ''),
        trim(preset_storage_bucket),
        trim(preset_file_path),
        coalesce(preset_published, true),
        auth.uid()
    )
    returning *
    into inserted_row;

    return inserted_row;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
    new.updated_at = now();
    return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.sync_marketplace_author_profile(p_display_name text, p_avatar_url text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
    if auth.uid() is null then
        raise exception 'Not authenticated';
    end if;

    insert into public.marketplace_author_profiles (user_id, display_name, avatar_url, updated_at)
    values (
        auth.uid(),
        coalesce(nullif(trim(p_display_name), ''), 'Discord user'),
        nullif(trim(p_avatar_url), ''),
        now()
    )
    on conflict (user_id) do update
    set display_name = excluded.display_name,
        avatar_url = excluded.avatar_url,
        updated_at = now();

    update public.marketplace_presets
    set author_name = coalesce(nullif(trim(p_display_name), ''), author_name),
        author_avatar_url = nullif(trim(p_avatar_url), ''),
        updated_at = now()
    where author_user_id = auth.uid();
end;
$function$
;

CREATE OR REPLACE FUNCTION public.sync_preset_likes_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
    update public.marketplace_presets
    set likes_count = (
        select count(*)
        from public.preset_likes pl
        where pl.preset_id = coalesce(new.preset_id, old.preset_id)
    ),
    updated_at = now()
    where id = coalesce(new.preset_id, old.preset_id);

    return coalesce(new, old);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.toggle_marketplace_preset_like(target_preset_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
    recent_like_count integer;
    liked_now boolean;
    updated_likes_count integer;
begin
    if auth.uid() is null then
        raise exception 'Authentication required.'
            using errcode = '42501';
    end if;

    if not exists (
        select 1
        from public.marketplace_presets
        where id = target_preset_id
          and published = true
    ) then
        raise exception 'Preset not found.'
            using errcode = 'P0001';
    end if;

    select count(*)
    into recent_like_count
    from public.marketplace_like_events
    where user_id = auth.uid()
      and preset_id = target_preset_id
      and created_at >= now() - interval '2500 milliseconds';

    if recent_like_count > 0 then
        raise exception 'Like rate limit exceeded. Try again in a moment.'
            using errcode = 'P0001';
    end if;

    insert into public.marketplace_like_events (user_id, preset_id)
    values (auth.uid(), target_preset_id);

    if exists (
        select 1
        from public.preset_likes
        where preset_id = target_preset_id
          and user_id = auth.uid()
    ) then
        delete from public.preset_likes
        where preset_id = target_preset_id
          and user_id = auth.uid();
        liked_now := false;
    else
        insert into public.preset_likes (preset_id, user_id)
        values (target_preset_id, auth.uid());
        liked_now := true;
    end if;

    select count(*)
    into updated_likes_count
    from public.preset_likes
    where preset_id = target_preset_id;

    update public.marketplace_presets
    set likes_count = updated_likes_count,
        updated_at = now()
    where id = target_preset_id;

    return jsonb_build_object(
        'liked', liked_now,
        'likes_count', updated_likes_count
    );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.update_marketplace_preset_metadata(target_preset_id uuid, preset_name text, preset_description text, preset_tags text[], preset_game_version text, preset_pathmind_version text, preset_published boolean DEFAULT NULL::boolean, preset_storage_bucket text DEFAULT NULL::text, preset_file_path text DEFAULT NULL::text)
 RETURNS public.marketplace_presets
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
    updated_row public.marketplace_presets;
    normalized_tags text[];
begin
    if auth.uid() is null then
        raise exception 'Authentication required.'
            using errcode = '42501';
    end if;

    if coalesce(trim(preset_name), '') = '' then
        raise exception 'Preset name is required.'
            using errcode = 'P0001';
    end if;

    select coalesce(array_agg(tag), array[]::text[])
    into normalized_tags
    from (
        select distinct left(trim(tag), 32) as tag
        from unnest(coalesce(preset_tags, array[]::text[])) as tag
        where coalesce(trim(tag), '') <> ''
        limit 12
    ) normalized;

    update public.marketplace_presets
    set name = left(trim(preset_name), 64),
        description = left(coalesce(trim(preset_description), ''), 180),
        tags = normalized_tags,
        game_version = nullif(trim(preset_game_version), ''),
        pathmind_version = nullif(trim(preset_pathmind_version), ''),
        published = coalesce(preset_published, published),
        storage_bucket = coalesce(nullif(trim(preset_storage_bucket), ''), storage_bucket),
        file_path = coalesce(nullif(trim(preset_file_path), ''), file_path),
        updated_at = now()
    where id = target_preset_id
      and (
          author_user_id = auth.uid()
          or public.is_marketplace_moderator(auth.uid())
      )
    returning *
    into updated_row;

    if updated_row.id is null then
        raise exception 'Preset not found or not owned by current user.'
            using errcode = '42501';
    end if;

    return updated_row;
end;
$function$
;

grant delete on table "public"."marketplace_author_profiles" to "anon";

grant insert on table "public"."marketplace_author_profiles" to "anon";

grant references on table "public"."marketplace_author_profiles" to "anon";

grant select on table "public"."marketplace_author_profiles" to "anon";

grant trigger on table "public"."marketplace_author_profiles" to "anon";

grant truncate on table "public"."marketplace_author_profiles" to "anon";

grant update on table "public"."marketplace_author_profiles" to "anon";

grant delete on table "public"."marketplace_author_profiles" to "authenticated";

grant insert on table "public"."marketplace_author_profiles" to "authenticated";

grant references on table "public"."marketplace_author_profiles" to "authenticated";

grant select on table "public"."marketplace_author_profiles" to "authenticated";

grant trigger on table "public"."marketplace_author_profiles" to "authenticated";

grant truncate on table "public"."marketplace_author_profiles" to "authenticated";

grant update on table "public"."marketplace_author_profiles" to "authenticated";

grant delete on table "public"."marketplace_author_profiles" to "service_role";

grant insert on table "public"."marketplace_author_profiles" to "service_role";

grant references on table "public"."marketplace_author_profiles" to "service_role";

grant select on table "public"."marketplace_author_profiles" to "service_role";

grant trigger on table "public"."marketplace_author_profiles" to "service_role";

grant truncate on table "public"."marketplace_author_profiles" to "service_role";

grant update on table "public"."marketplace_author_profiles" to "service_role";

grant delete on table "public"."marketplace_download_events" to "service_role";

grant insert on table "public"."marketplace_download_events" to "service_role";

grant references on table "public"."marketplace_download_events" to "service_role";

grant select on table "public"."marketplace_download_events" to "service_role";

grant trigger on table "public"."marketplace_download_events" to "service_role";

grant truncate on table "public"."marketplace_download_events" to "service_role";

grant update on table "public"."marketplace_download_events" to "service_role";

grant delete on table "public"."marketplace_like_events" to "service_role";

grant insert on table "public"."marketplace_like_events" to "service_role";

grant references on table "public"."marketplace_like_events" to "service_role";

grant select on table "public"."marketplace_like_events" to "service_role";

grant trigger on table "public"."marketplace_like_events" to "service_role";

grant truncate on table "public"."marketplace_like_events" to "service_role";

grant update on table "public"."marketplace_like_events" to "service_role";

grant delete on table "public"."marketplace_presets" to "anon";

grant insert on table "public"."marketplace_presets" to "anon";

grant references on table "public"."marketplace_presets" to "anon";

grant select on table "public"."marketplace_presets" to "anon";

grant trigger on table "public"."marketplace_presets" to "anon";

grant truncate on table "public"."marketplace_presets" to "anon";

grant update on table "public"."marketplace_presets" to "anon";

grant delete on table "public"."marketplace_presets" to "authenticated";

grant insert on table "public"."marketplace_presets" to "authenticated";

grant references on table "public"."marketplace_presets" to "authenticated";

grant select on table "public"."marketplace_presets" to "authenticated";

grant trigger on table "public"."marketplace_presets" to "authenticated";

grant truncate on table "public"."marketplace_presets" to "authenticated";

grant update on table "public"."marketplace_presets" to "authenticated";

grant delete on table "public"."marketplace_presets" to "service_role";

grant insert on table "public"."marketplace_presets" to "service_role";

grant references on table "public"."marketplace_presets" to "service_role";

grant select on table "public"."marketplace_presets" to "service_role";

grant trigger on table "public"."marketplace_presets" to "service_role";

grant truncate on table "public"."marketplace_presets" to "service_role";

grant update on table "public"."marketplace_presets" to "service_role";

grant delete on table "public"."marketplace_publish_events" to "service_role";

grant insert on table "public"."marketplace_publish_events" to "service_role";

grant references on table "public"."marketplace_publish_events" to "service_role";

grant select on table "public"."marketplace_publish_events" to "service_role";

grant trigger on table "public"."marketplace_publish_events" to "service_role";

grant truncate on table "public"."marketplace_publish_events" to "service_role";

grant update on table "public"."marketplace_publish_events" to "service_role";

grant delete on table "public"."marketplace_roles" to "anon";

grant insert on table "public"."marketplace_roles" to "anon";

grant references on table "public"."marketplace_roles" to "anon";

grant select on table "public"."marketplace_roles" to "anon";

grant trigger on table "public"."marketplace_roles" to "anon";

grant truncate on table "public"."marketplace_roles" to "anon";

grant update on table "public"."marketplace_roles" to "anon";

grant delete on table "public"."marketplace_roles" to "authenticated";

grant insert on table "public"."marketplace_roles" to "authenticated";

grant references on table "public"."marketplace_roles" to "authenticated";

grant select on table "public"."marketplace_roles" to "authenticated";

grant trigger on table "public"."marketplace_roles" to "authenticated";

grant truncate on table "public"."marketplace_roles" to "authenticated";

grant update on table "public"."marketplace_roles" to "authenticated";

grant delete on table "public"."marketplace_roles" to "service_role";

grant insert on table "public"."marketplace_roles" to "service_role";

grant references on table "public"."marketplace_roles" to "service_role";

grant select on table "public"."marketplace_roles" to "service_role";

grant trigger on table "public"."marketplace_roles" to "service_role";

grant truncate on table "public"."marketplace_roles" to "service_role";

grant update on table "public"."marketplace_roles" to "service_role";

grant delete on table "public"."preset_likes" to "anon";

grant insert on table "public"."preset_likes" to "anon";

grant references on table "public"."preset_likes" to "anon";

grant select on table "public"."preset_likes" to "anon";

grant trigger on table "public"."preset_likes" to "anon";

grant truncate on table "public"."preset_likes" to "anon";

grant update on table "public"."preset_likes" to "anon";

grant delete on table "public"."preset_likes" to "authenticated";

grant insert on table "public"."preset_likes" to "authenticated";

grant references on table "public"."preset_likes" to "authenticated";

grant select on table "public"."preset_likes" to "authenticated";

grant trigger on table "public"."preset_likes" to "authenticated";

grant truncate on table "public"."preset_likes" to "authenticated";

grant update on table "public"."preset_likes" to "authenticated";

grant delete on table "public"."preset_likes" to "service_role";

grant insert on table "public"."preset_likes" to "service_role";

grant references on table "public"."preset_likes" to "service_role";

grant select on table "public"."preset_likes" to "service_role";

grant trigger on table "public"."preset_likes" to "service_role";

grant truncate on table "public"."preset_likes" to "service_role";

grant update on table "public"."preset_likes" to "service_role";


  create policy "Public can read marketplace author profiles"
  on "public"."marketplace_author_profiles"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "Users can manage own marketplace author profile"
  on "public"."marketplace_author_profiles"
  as permissive
  for all
  to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "Marketplace moderators can read all presets"
  on "public"."marketplace_presets"
  as permissive
  for select
  to authenticated
using (public.is_marketplace_moderator(auth.uid()));



  create policy "Owners can read their marketplace presets"
  on "public"."marketplace_presets"
  as permissive
  for select
  to authenticated
using ((author_user_id = auth.uid()));



  create policy "Public can read published marketplace presets"
  on "public"."marketplace_presets"
  as permissive
  for select
  to anon, authenticated
using ((published = true));



  create policy "Public can read published presets"
  on "public"."marketplace_presets"
  as permissive
  for select
  to anon, authenticated
using ((published = true));



  create policy "authenticated users can delete own presets"
  on "public"."marketplace_presets"
  as permissive
  for delete
  to authenticated
using ((author_user_id = auth.uid()));



  create policy "authenticated users can insert own presets"
  on "public"."marketplace_presets"
  as permissive
  for insert
  to authenticated
with check ((author_user_id = auth.uid()));



  create policy "authenticated users can read own presets"
  on "public"."marketplace_presets"
  as permissive
  for select
  to authenticated
using (((published = true) OR (author_user_id = auth.uid())));



  create policy "authenticated users can update own presets"
  on "public"."marketplace_presets"
  as permissive
  for update
  to authenticated
using ((author_user_id = auth.uid()))
with check ((author_user_id = auth.uid()));



  create policy "published presets are publicly readable"
  on "public"."marketplace_presets"
  as permissive
  for select
  to public
using ((published = true));



  create policy "Marketplace admins manage roles"
  on "public"."marketplace_roles"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.marketplace_roles actor
  WHERE ((actor.user_id = auth.uid()) AND (actor.role = 'admin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM public.marketplace_roles actor
  WHERE ((actor.user_id = auth.uid()) AND (actor.role = 'admin'::text)))));



  create policy "Users can read own marketplace role"
  on "public"."marketplace_roles"
  as permissive
  for select
  to authenticated
using ((user_id = auth.uid()));



  create policy "Authenticated users can like presets"
  on "public"."preset_likes"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "Authenticated users can unlike their own likes"
  on "public"."preset_likes"
  as permissive
  for delete
  to authenticated
using ((auth.uid() = user_id));



  create policy "Public can read likes"
  on "public"."preset_likes"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "Users can delete their own preset likes"
  on "public"."preset_likes"
  as permissive
  for delete
  to authenticated
using ((user_id = auth.uid()));



  create policy "Users can insert their own preset likes"
  on "public"."preset_likes"
  as permissive
  for insert
  to authenticated
with check ((user_id = auth.uid()));



  create policy "Users can read their own preset likes"
  on "public"."preset_likes"
  as permissive
  for select
  to authenticated
using ((user_id = auth.uid()));


CREATE TRIGGER marketplace_presets_set_updated_at BEFORE UPDATE ON public.marketplace_presets FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER preset_likes_sync_count_delete AFTER DELETE ON public.preset_likes FOR EACH ROW EXECUTE FUNCTION public.sync_preset_likes_count();

CREATE TRIGGER preset_likes_sync_count_insert AFTER INSERT ON public.preset_likes FOR EACH ROW EXECUTE FUNCTION public.sync_preset_likes_count();


  create policy "Marketplace moderators can delete preset storage"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = ANY (ARRAY['graphs'::text, 'private_graphs'::text])) AND public.is_marketplace_moderator(auth.uid())));



  create policy "Marketplace moderators can insert preset storage"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = ANY (ARRAY['graphs'::text, 'private_graphs'::text])) AND public.is_marketplace_moderator(auth.uid())));



  create policy "Marketplace moderators can read preset storage"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = ANY (ARRAY['graphs'::text, 'private_graphs'::text])) AND public.is_marketplace_moderator(auth.uid())));



  create policy "Marketplace moderators can update preset storage"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = ANY (ARRAY['graphs'::text, 'private_graphs'::text])) AND public.is_marketplace_moderator(auth.uid())))
with check (((bucket_id = ANY (ARRAY['graphs'::text, 'private_graphs'::text])) AND public.is_marketplace_moderator(auth.uid())));



  create policy "Users can delete their own private graphs"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'private_graphs'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



  create policy "Users can read their own private graphs"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'private_graphs'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



  create policy "Users can update their own private graphs"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'private_graphs'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)))
with check (((bucket_id = 'private_graphs'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



  create policy "Users can upload their own private graphs"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'private_graphs'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



  create policy "Users delete own author avatar object"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'marketplace-author-avatars'::text) AND (split_part(name, '/'::text, 1) = (auth.uid())::text)));



  create policy "Users update own author avatar object"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'marketplace-author-avatars'::text) AND (split_part(name, '/'::text, 1) = (auth.uid())::text)))
with check (((bucket_id = 'marketplace-author-avatars'::text) AND (split_part(name, '/'::text, 1) = (auth.uid())::text)));



  create policy "Users upload own author avatar object"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'marketplace-author-avatars'::text) AND (split_part(name, '/'::text, 1) = (auth.uid())::text)));



  create policy "authenticated users can delete graph files"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using ((bucket_id = 'graphs'::text));



  create policy "authenticated users can update graph files"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using ((bucket_id = 'graphs'::text))
with check ((bucket_id = 'graphs'::text));



  create policy "authenticated users can upload graph files"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'graphs'::text));



  create policy "graph files are publicly readable"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'graphs'::text));



